name: Java CI

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '21'
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    gradle-version: wrapper
            -   name: Build with Gradle
                run: ./gradlew build
